export const words = [
    "🦉",
    "Awesome",
    "Brilliant",
    "Amazing",
    "cool",
    "exciting",
    "😍🦉",
    "Stay creative",
    "Awesome Hoot",
    "Sweet",
    "🦉😀👍🏻",
    "kewl",
    "beautiful",
    "you blew me away",
    "Love it!",
    "Keep rolling!!",
    "😍",
    "Join the Club",
    "confidence is key , throw the key away 🥰😘😊",
    "Just keep smiling 💖✌🏻😘",
    "this inspired me🧚‍♀️💖",
    "Practice makes perfect 🥰",
    "You’re on top of the world",
    "wow look at your talent!",
    "Neat!",
    "👍🏻",
    "Never seen a selfie of yours that I don’t like.",
    "You are the coolest.",
    "😀😍",
    "Blessing your Soapbox feed once again",
    "The hottest pal in the town",
    "Keep Shining",
    "👏🏻",
    "make the most of it all",
    "come join us",
    "awesome content",
    "wicked hoot",
    "where's the MORE",
    "😊💗",
    "who did what and why",
    "where are we going",
    "👏🏻👍🏻😀",
    "dont know why but I like this hoot",
    "Hoots are bad ass",
    "my comments are my own",
    "wheres your club?",
    "Twitter Twitter yadda yadda",
    "💗",
    "InstaWHAT....",
    "Keep sharing the wicked content",
    "Jumpin' head first",
    "who what and when",
    "bring the noise",
    "😀",
    "Funky",
    "sweet hoot",
    "saucy but kewl",
    "hey , cool hoot",
    "keep posting sweet stuff",
    "😍😍😍",
    "Watching the waves",
    "Sun is shinning",
    "Post more Hoots!",
    "🦉🦉",
    "Life is life",
    "love it",
    "looking good",
    "sharp",
    "🙏🏻",
    "whaaaatttt",
    "bring it dont sing it",
    "😍💗",
    "woooowwww",
    "👍🏻👏🏻",
    "whoooaaaaaaa",
    "😊",
    "WTF",
    "🙏🏻👏🏻",
    "FOMO",
    "Bringing it round and round",
    "👏🏻🙏🏻😊",
]

export const numbers = [
    "4",
    "89",
    "0",
    "11",
    "174",
    "9g3",
    "007",
    "37",
    "p1",
    "8",
    "55",
    "7",
    "d7",
    "00",
    "cc",
    "1gea80",
    "fB",
    "ttt",
    "33",
    "9",
    "POP9",
    "8gig",
    "dfi1",
    "109",
    "s2",
    "67",
    "t7",
    "666",
    "gg1",
    "A2g",
    "23",
    "4b",
    "78",
    "ca08",
    "8acy",
    "7c9a",
    "vd7y",
    "c",
    "80uv",
    "dv89",
    "vd8",
    "3r",
    "893",
    "08d",
    "d80v",
    "231",
    "97c",
    "fbs08",
    "a97c",
    "atnt",
    "9dc08",
    "av1",
    "a8y",
    "85q",
    "a7s",
    "vda",
    "3567",
    "22",
    "vad08",
    "983",
    "75c",
    "189",
    "809",
    "cs5",
    "c087",
    "532bn",
    "8cs6r",
    "csD",
    "v0",
    "vga7",
    "iu76",
    "dv5",
    "hr42",
    "973",
    "2355",
    "0894",
    "661",
    "2972",
    "HV46",
    "3sf",
    "08yh",
    "648",
    "sd",
    "86f",
    "vd86",
    "98ty",
    "fd784",
    "fds793",
    "899r",
    "vs75b",
    "869s",
    "s87",
    "8967c",
    "123",
    "8n95v",
    "7655",
    "44de",
    "4ch",
    "mo1",
    "0h",
    "6248",
    "sd43",
    "86cf",
    "v56",
    "52ty",
    "f84",
    "y93",
    "9r",
    "v5b",
    "836s",
    "ss7",
    "87c",
    "1sb3",
    "25v",
    "7t55",
    "466e",
    "442",
    "m241",
    "m11",
    "0tt",
    "3438",
    "sxq23",
    "83f",
    "v36",
    "25ty",
    "6784",
    "gs3",
    "va32",
    "31tb",
    "3t6s",
    "t7",
    "8tc",
    "1gr",
    "2gq",
    "7525",
    "2te",
    "4ef",
    "ma3qd1",
]