export const words = [
    "🦉",
    "Awesome",
    "Brilliant",
    "Amazing",
    "cool",
    "exciting",
    "😍🦉",
    "Stay creative",
    "Awesome Hoot",
    "Sweet",
    "🦉😀👍🏻",
    "kewl",
    "beautiful",
    "you blew me away",
    "Love it!",
    "Keep rolling!!",
    "😍",
    "Join the Club",
    "confidence is key , throw the key away 🥰😘😊",
    "Just keep smiling 💖✌🏻😘",
    "this inspired me🧚‍♀️💖",
    "Practice makes perfect 🥰",
    "You’re on top of the world",
    "wow look at your talent!",
    "Neat!",
    "👍🏻",
    "Never seen a selfie of yours that I don’t like.",
    "You are the coolest.",
    "😀😍",
    "Blessing your Soapbox feed once again",
    "The hottest pal in the town",
    "Keep Shining",
    "👏🏻",
    "make the most of it all",
    "come join us",
    "awesome content",
    "wicked hoot",
    "where's the MORE",
    "😊💗",
    "who did what and why",
    "where are we going",
    "👏🏻👍🏻😀",
    "dont know why but I like this hoot",
    "Hoots are bad ass",
    "my comments are my own",
    "wheres your club?",
    "Twitter Twitter yadda yadda",
    "💗",
    "InstaWHAT....",
    "Keep sharing the wicked content",
    "Jumpin' head first",
    "who what and when",
    "bring the noise",
    "😀",
    "Funky",
    "sweet hoot",
    "saucy but kewl",
    "hey , cool hoot",
    "keep posting sweet stuff",
    "😍😍😍",
    "Watching the waves",
    "Sun is shinning",
    "Post more Hoots!",
    "🦉🦉",
    "Life is life",
    "love it",
    "looking good",
    "sharp",
    "🙏🏻",
    "whaaaatttt",
    "bring it dont sing it",
    "😍💗",
    "woooowwww",
    "👍🏻👏🏻",
    "whoooaaaaaaa",
    "😊",
    "WTF",
    "🙏🏻👏🏻",
    "FOMO",
    "Bringing it round and round",
    "👏🏻🙏🏻😊",
]